<?php

return [
    'produk' => [
        'beras premium',
        'beras medium',
        'gula pasir',
        'minyak grg cur',
        'minyak goreng bimoli',
        'daging sapi murni',
        'daging sapi kw',
        'daging ayam ras',
        'daging ayam kampung',
        'telur ayam ras',
        'telur ayam kampung',
        'susu bubuk indomilk',
        'susu bubuk dancow',
        'skm bendera',
        'skm indomilk',
        'jagung pipilan',
        'terigu bogasari',
        'kedelai lokal',
        'kedelai impor',
        'cabai merah besar',
        'cabai merah keriting',
        'cabai rawit merah',
        'cabai rawit hijau',
        'bawang merah',
        'bawang putih',
        'bawang kating',
        'ikan kembung',
        'ikan teri',
        'ikan bandeng',
        'garam bata',
        'garam halus',
        'kacang tanah',
        'kacang hijau',
        'minyak kita',
        'ikan tongkol',
        'tempe',
        'tahu mentah putih',
        'udang segar',
        'pisang',
        'jeruk lokal',
        'ketela pohon',
        'bawang bombay',
    ],
    'barang' => [
        'beras_premium',
        'beras_medium',
        'gula_pasir',
        'minyak_grg_cur',
        'minyak_goreng_bimoli',
        'daging_sapi_murni',
        'daging_sapi_kw',
        'daging_ayam_ras',
        'daging_ayam_kampung',
        'telur_ayam_ras',
        'telur_ayam_kampung',
        'susu_bubuk_indomilk',
        'susu_bubuk_dancow',
        'skm_bendera',
        'skm_indomilk',
        'jagung_pipilan',
        'terigu_bogasari',
        'kedelai_lokal',
        'kedelai_impor',
        'cabai_merah_besar',
        'cabai_merah_keriting',
        'cabai_rawit_merah',
        'cabai_rawit_hijau',
        'bawang_merah',
        'bawang_putih',
        'bawang_kating',
        'ikan_kembung',
        'ikan_teri',
        'ikan_bandeng',
        'garam_bata',
        'garam_halus',
        'kacang_tanah',
        'kacang_hijau',
        'minyak_kita',
        'ikan_tongkol',
        'tempe',
        'tahu_mentah_putih',
        'udang_segar',
        'pisang',
        'jeruk_lokal',
        'ketela_pohon',
        'bawang_bombay',
    ]
];
